drc/config/routes.rb
Drc::Application.routes.draw do
  resources :inventory_entries

  resources :order_items

  resources :orders  do
    resource :order_items
  end

  resources :clients do
    collection do
      get 'search_clients'
    end
  end

  resources :products   do
    collection do
      get 'search_products'
    end
  end

  resources :subgroups

  resources :groups

  resources :states

  resources :producers

  devise_for :users, :path_prefix => "my"  ,  :controllers => { :registrations => "my/users/registrations" }
  resources :users
  resources :roles

   root :to => 'home#index'

end

drc/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.roles? :administrador
      can :manage, :all
    elsif user.roles? :vendedor
      can :manage, State
      can :manage, Client
      can :manage, Producer
      can :manage, Group
      can :manage, Subgroup
      can :manage, Order
      can :manage, OrderItem
    else
      can :read, :all
    end

  end




end

drc/app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :cep, :city, :cpf, :name, :phone_number ,:state_id
  validates :name,:address, :cep, :city , :presence => true
  validates :phone_number, :presence => true, :numericality => true
  usar_como_cpf :cpf
end

drc/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name, :message => "obrigatorio"

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/inventory_entry.rb
class InventoryEntry < ActiveRecord::Base
  belongs_to :product
  attr_accessible :amount, :lot, :purchase_price, :sale_price
end

drc/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client

  has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  attr_accessible :delivery_date, :order_date, :value, :client_id, :client


  def total_order
    total = 0
    self.order_items.each  do |p|
        total += p.product.sale_price * p.amount
    end
    total
  end

end

drc/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  attr_accessible :amount, :product_id, :order_id
end

drc/app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :city, :cnpj, :cpf, :email, :mobile_number, :name, :phone_number, :state_id
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  validates_presence_of :name, :address,:mobile_number
  validates_email_format_of :email

  extend FriendlyId
    friendly_id :name, use: :slugged

end

drc/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :group
  belongs_to :subgroup
  belongs_to :producer
  attr_accessible :amount, :barcode, :code, :cost_price, :name, :sale_price, :group_id, :subgroup_id,:producer_id

  usar_como_dinheiro :cost_price, :sale_price

  extend FriendlyId
  friendly_id :name, use: :slugged

  def name_code
    "#{self.code} - #{self.name}"
  end

end

drc/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  attr_accessible :name


end

drc/app/models/state.rb
class State < ActiveRecord::Base
  resourcify
  attr_accessible :acronym, :name
  extend FriendlyId
    friendly_id :name, use: :slugged
end

drc/app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name, :message => 'obrigatorio'

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # attr_accessible :title, :body

  def roles?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

drc/app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize, :f => builder)
    end
    #link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

end

drc/app/helpers/clients_helper.rb
module ClientsHelper
end

drc/app/helpers/groups_helper.rb
module GroupsHelper
end

drc/app/helpers/orders_helper.rb
module OrdersHelper

end

drc/app/helpers/producers_helper.rb
module ProducersHelper
end

drc/app/helpers/products_helper.rb
module ProductsHelper
end

drc/app/helpers/states_helper.rb
module StatesHelper
end

drc/app/helpers/subgroups_helper.rb
module SubgroupsHelper
end

drc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drc</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>



  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <div class="btn-toolbar">
    <div class="btn-group">
      <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
        Estoque
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <!-- dropdown menu links -->
        <li><%= link_to "Produtos", products_path %></li>
        <li><%= link_to "Fabricante", producers_path %></li>
        <li><%= link_to "Grupo de Produto", groups_path %></li>
        <li><%= link_to "SubGrupo de Produto", subgroups_path %></li>
        <li><%= link_to "Clientes", clients_path %></li>


      </ul>
    </div>


    <div class="btn-group">
      <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
      Segurança
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <!-- dropdown menu links -->
        <li><%= link_to "Usuários", users_path %></li>
      </ul>
    </div>

    <% if user_signed_in? %>
        <div class="btn-group">

          <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
          Administração
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        </div>
    <% end %>
  </div>

  <!--Body content-->
  <%= yield %>
</div>
</body>
</html>

drc/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>



  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <!--Body content-->
  <%= yield %>
</div>
</body>
</html>