drc/config/routes.rb
Drc::Application.routes.draw do
  resources :inventory_entries

  resources :order_items

  resources :orders  do
    resource :order_items
  end

  resources :clients do
    collection do
      get 'search_clients'
    end
  end

  resources :products   do
    collection do
      get 'search_products'
    end
  end

  resources :subgroups

  resources :groups

  resources :states

  resources :producers

  devise_for :users, :path_prefix => "my"  ,  :controllers => { :registrations => "my/users/registrations" }
  resources :users
  resources :roles

   root :to => 'home#index'

end

drc/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.roles? :administrador
      can :manage, :all
    elsif user.roles? :vendedor
      can :manage, State
      can :manage, Client
      can :manage, Producer
      can :manage, Group
      can :manage, Subgroup
      can :manage, Order
      can :manage, OrderItem
    else
      can :read, :all
    end

  end




end

drc/app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :cep, :city, :cpf, :name, :phone_number ,:state_id
  validates :name,:address, :cep, :city , :presence => true
  validates :phone_number, :presence => true, :numericality => true
  usar_como_cpf :cpf
end

drc/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name, :message => "obrigatorio"

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/inventory_entry.rb
class InventoryEntry < ActiveRecord::Base
  belongs_to :product
  attr_accessible :amount, :lot, :purchase_price, :sale_price
end

drc/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client

  has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  attr_accessible :delivery_date, :order_date, :value, :client_id, :client


  def total_order
    total = 0
    self.order_items.each  do |p|
        total += p.product.sale_price * p.amount
    end
    total
  end

end

drc/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  attr_accessible :amount, :product_id, :order_id
end

drc/app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :city, :cnpj, :cpf, :email, :mobile_number, :name, :phone_number, :state_id
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  validates_presence_of :name, :address,:mobile_number
  validates_email_format_of :email

  extend FriendlyId
    friendly_id :name, use: :slugged

end

drc/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :group
  belongs_to :subgroup
  belongs_to :producer
  attr_accessible :amount, :barcode, :code, :cost_price, :name, :sale_price, :group_id, :subgroup_id,:producer_id

  usar_como_dinheiro :cost_price, :sale_price

  extend FriendlyId
  friendly_id :name, use: :slugged

  def name_code
    "#{self.code} - #{self.name}"
  end

end

drc/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  attr_accessible :name


end

drc/app/models/state.rb
class State < ActiveRecord::Base
  resourcify
  attr_accessible :acronym, :name
  extend FriendlyId
    friendly_id :name, use: :slugged
end

drc/app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name, :message => 'obrigatorio'

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # attr_accessible :title, :body

  def roles?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

drc/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

drc/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json


  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    params[:order].delete(:cliente)
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

drc/app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize, :f => builder)
    end
    #link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

end

drc/app/helpers/clients_helper.rb
module ClientsHelper
end

drc/app/helpers/groups_helper.rb
module GroupsHelper
end

drc/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

drc/app/helpers/orders_helper.rb
module OrdersHelper

end

drc/app/helpers/producers_helper.rb
module ProducersHelper
end

drc/app/helpers/products_helper.rb
module ProductsHelper
end

drc/app/helpers/states_helper.rb
module StatesHelper
end

drc/app/helpers/subgroups_helper.rb
module SubgroupsHelper
end

drc/app/views/orders/_form.html.erb
<%= form_for(@order, :html=>{:class=>'form'}) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="ui-widget">
    <%= f.label :client %><br />
    <input id="client"  type="text"/>

    <input id="order_client_id" name="order[client_id]" type="hidden"/>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br />
    <%= f.text_field :order_date, :class=>"datepicker" %>
  </div>
  <div class="field">
    <%= f.label :delivery_date %><br />
    <%= f.text_field :delivery_date , :class=>"datepicker" %>
  </div>

     <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

drc/app/views/orders/_order_item.html.erb
<div class="ui-widget">
  <%= f.label :product %><br />
  <%= f.text_field :product  %>
  <%= f.hidden_field :product_id  %>


</div>

<div class="ui-widget">
  <%= f.label :amount %><br />
  <%= f.text_field :amount  %>

</div>

drc/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

drc/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Client</th>
    <th>Value</th>
    <th>Order date</th>
    <th>Delivery date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.client %></td>
    <td><%= order.value %></td>
    <td><%= order.order_date %></td>
    <td><%= order.delivery_date %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

drc/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

drc/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @order.client.name %>
</p>

<p>
  <b>Value:</b>
  <%= @order.total_order %>
</p>

<p>
  <b>Order date:</b>
  <%= @order.order_date %>
</p>

<p>
  <b>Delivery date:</b>
  <%= @order.delivery_date %>
</p>

<h1>Itens</h1>

<table class="table table-striped table-hover">
  <tr>
    <th>Produto</th>
    <th>Quantidade</th>
    <th></th>
    <th></th>
  </tr>

  <% @order.order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product.name %></td>
        <td><%= order_item.amount %></td>
        <td><%= link_to '',edit_order_item_path(order_item),  :class=>"icon-edit" %></td>
        <td><%= link_to '',order_item , :class=>"icon-trash", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />



<%= link_to 'Adicionar Itens', new_order_order_items_path(@order.id)  %>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>