drc/config/routes.rb
Drc::Application.routes.draw do
  resources :inventory_entries

  resources :order_items

  resources :orders  do
    resource :order_items
  end

  resources :clients do
    collection do
      get 'search_clients'
    end
  end

  resources :products   do
    collection do
      get 'search_products'
    end
  end

  resources :subgroups

  resources :groups

  resources :states

  resources :producers

  devise_for :users, :path_prefix => "my"  ,  :controllers => { :registrations => "my/users/registrations" }
  resources :users
  resources :roles

   root :to => 'home#index'

end

drc/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.roles? :administrador
      can :manage, :all
    elsif user.roles? :vendedor
      can :manage, State
      can :manage, Client
      can :manage, Producer
      can :manage, Group
      can :manage, Subgroup
      can :manage, Order
      can :manage, OrderItem
    else
      can :read, :all
    end

  end




end

drc/app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :cep, :city, :cpf, :name, :phone_number ,:state_id
  validates :name,:address, :cep, :city , :presence => true
  validates :phone_number, :presence => true, :numericality => true
  usar_como_cpf :cpf
end

drc/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name, :message => "obrigatorio"

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/inventory_entry.rb
class InventoryEntry < ActiveRecord::Base
  belongs_to :product
  attr_accessible :amount, :lot, :purchase_price, :sale_price
end

drc/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client

  has_many :order_items, :dependent => :destroy
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  attr_accessible :delivery_date, :order_date, :value, :client_id, :client


  def total_order
    total = 0
    self.order_items.each  do |p|
        total += p.product.sale_price * p.amount
    end
    total
  end

end

drc/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  attr_accessible :amount, :product_id, :order_id
end

drc/app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :state
  attr_accessible :address, :city, :cnpj, :cpf, :email, :mobile_number, :name, :phone_number, :state_id
  usar_como_cpf :cpf
  usar_como_cnpj :cnpj
  validates_presence_of :name, :address,:mobile_number
  validates_email_format_of :email

  extend FriendlyId
    friendly_id :name, use: :slugged

end

drc/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :group
  belongs_to :subgroup
  belongs_to :producer
  attr_accessible :amount, :barcode, :code, :cost_price, :name, :sale_price, :group_id, :subgroup_id,:producer_id

  usar_como_dinheiro :cost_price, :sale_price

  extend FriendlyId
  friendly_id :name, use: :slugged

  def name_code
    "#{self.code} - #{self.name}"
  end

end

drc/app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify

  attr_accessible :name


end

drc/app/models/state.rb
class State < ActiveRecord::Base
  resourcify
  attr_accessible :acronym, :name
  extend FriendlyId
    friendly_id :name, use: :slugged
end

drc/app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name, :message => 'obrigatorio'

  extend FriendlyId
  friendly_id :name, use: :slugged
end

drc/app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # attr_accessible :title, :body

  def roles?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

drc/app/controllers/inventory_entries_controller.rb
class InventoryEntriesController < ApplicationController
  # GET /inventory_entries
  # GET /inventory_entries.json
  def index
    @inventory_entries = InventoryEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_entries }
    end
  end

  # GET /inventory_entries/1
  # GET /inventory_entries/1.json
  def show
    @inventory_entry = InventoryEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory_entry }
    end
  end

  # GET /inventory_entries/new
  # GET /inventory_entries/new.json
  def new
    @inventory_entry = InventoryEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_entry }
    end
  end

  # GET /inventory_entries/1/edit
  def edit
    @inventory_entry = InventoryEntry.find(params[:id])
  end

  # POST /inventory_entries
  # POST /inventory_entries.json
  def create
    @inventory_entry = InventoryEntry.new(params[:inventory_entry])

    respond_to do |format|
      if @inventory_entry.save
        format.html { redirect_to @inventory_entry, notice: 'Inventory entry was successfully created.' }
        format.json { render json: @inventory_entry, status: :created, location: @inventory_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_entries/1
  # PUT /inventory_entries/1.json
  def update
    @inventory_entry = InventoryEntry.find(params[:id])

    respond_to do |format|
      if @inventory_entry.update_attributes(params[:inventory_entry])
        format.html { redirect_to @inventory_entry, notice: 'Inventory entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_entries/1
  # DELETE /inventory_entries/1.json
  def destroy
    @inventory_entry = InventoryEntry.find(params[:id])
    @inventory_entry.destroy

    respond_to do |format|
      format.html { redirect_to inventory_entries_url }
      format.json { head :no_content }
    end
  end
end

drc/app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize, :f => builder)
    end
    #link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

end

drc/app/helpers/clients_helper.rb
module ClientsHelper
end

drc/app/helpers/groups_helper.rb
module GroupsHelper
end

drc/app/helpers/inventory_entries_helper.rb
module InventoryEntriesHelper
end

drc/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

drc/app/helpers/orders_helper.rb
module OrdersHelper

end

drc/app/helpers/producers_helper.rb
module ProducersHelper
end

drc/app/helpers/products_helper.rb
module ProductsHelper
end

drc/app/helpers/states_helper.rb
module StatesHelper
end

drc/app/helpers/subgroups_helper.rb
module SubgroupsHelper
end

drc/app/views/inventory_entries/_form.html.erb
<%= form_for(@inventory_entry) do |f| %>
  <% if @inventory_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_entry.errors.count, "error") %> prohibited this inventory_entry from being saved:</h2>

      <ul>
      <% @inventory_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br />
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :purchase_price %><br />
    <%= f.text_field :purchase_price %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :lot %><br />
    <%= f.number_field :lot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

drc/app/views/inventory_entries/edit.html.erb
<h1>Editing inventory_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_entry %> |
<%= link_to 'Back', inventory_entries_path %>

drc/app/views/inventory_entries/index.html.erb
<h1>Listing inventory_entries</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Sale price</th>
    <th>Purchase price</th>
    <th>Amount</th>
    <th>Lot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventory_entries.each do |inventory_entry| %>
  <tr>
    <td><%= inventory_entry.product %></td>
    <td><%= inventory_entry.sale_price %></td>
    <td><%= inventory_entry.purchase_price %></td>
    <td><%= inventory_entry.amount %></td>
    <td><%= inventory_entry.lot %></td>
    <td><%= link_to 'Show', inventory_entry %></td>
    <td><%= link_to 'Edit', edit_inventory_entry_path(inventory_entry) %></td>
    <td><%= link_to 'Destroy', inventory_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inventory entry', new_inventory_entry_path %>

drc/app/views/inventory_entries/new.html.erb
<h1>New inventory_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_entries_path %>

drc/app/views/inventory_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @inventory_entry.product %>
</p>

<p>
  <b>Sale price:</b>
  <%= @inventory_entry.sale_price %>
</p>

<p>
  <b>Purchase price:</b>
  <%= @inventory_entry.purchase_price %>
</p>

<p>
  <b>Amount:</b>
  <%= @inventory_entry.amount %>
</p>

<p>
  <b>Lot:</b>
  <%= @inventory_entry.lot %>
</p>


<%= link_to 'Edit', edit_inventory_entry_path(@inventory_entry) %> |
<%= link_to 'Back', inventory_entries_path %>